### ISSUE TITLE
Shield not gaining experience.

### ISSUE THREAD

**Issue by border999** [embeddedt/TinkerLeveling#10]
Am I just doing this wrong? I have attempted to use the shield to defend against skeleton arrows, massive slime body slams, and various other forms of damage including using the shield as a bludgeon. It has taken significant damage and has gained 0 experience the whole time.

**Comment by embeddedt** [comment]
I didn't realize Tinkers had custom shields. :sweat_smile: Shows how much I know about the mod...

Will look into this in due time.

**Comment by embeddedt** [comment]
Shields now gain XP in the latest 1.18 release.
