### ISSUE TITLE
1.16.5 version not working 

### ISSUE THREAD

**Issue by AbdulsttarFoxDev** [embeddedt/TinkerLeveling#13]
I tried install the mod but showed a Warning messages saying for me
File tinkerleveling-mc1.16.5-0.3.1-source.jar not a valid mod fill and i searched how solve that and the Solution of this proplm is install a  version From a mod but without word source and i tried install another file from curseforge but all the files is have word source

**Comment by embeddedt** [comment]
You should download the main file, not any additional files. Here is a link to the latest 1.16.5 version. If you cannot see any files besides the sources ones there is some issue with your game launcher.

https://www.curseforge.com/minecraft/mc-mods/tinker-leveling/files/4506902
