### ISSUE TITLE
Makes items unstackable.

### ISSUE THREAD

**Issue by MrFieldBird** [embeddedt/TinkerLeveling#2]
When i use this mod in my modpack crafted items don't stack with dropped ones, even all of their ID's and NBT tags are identical.

**Comment by embeddedt** [comment]
Does this occur with only this mod and Tinkers installed? I am having trouble reproducing it.

**Comment by CyperCyang** [comment]
> Does this occur with only this mod and Tinkers installed? I am having trouble reproducing it.

Yes, the problem will occur with only tinkers' dependency , tinkers and tinker leveling were installed.
The NBT shown in F3+H command is identical, but when I use the IBE Editor mod to check the items which cannot stack, it shows that the crafted items is ' {xxx.xxx{tag:{}}' and break item is '{xxx.xxx}' ,the difference make them unstackable. 
Mostly occurred on torch, ingot: the torch that be washed off or broken cannot stack with the crafted torch, but thrown and picked up crafted and not used torch can stack with the newly crafted torch.
Unable to fix this problem by placing items into a box but using a hopper to transfer the items in a box can fix the problem, this act will add the 'tag:{}' to none 'tag' items and make them stackable.
Besides, restart the game can change the NBT of the items player has and fix present problem, but the new items always have the problem.

**Comment by embeddedt** [comment]
Thanks, turned out to be a pretty obscure issue. It should be fixed in 0.3.0, but I don't think I can do anything about existing items.

**Comment by darchukoleksandr** [comment]
It's also relevant to 1.16.5 Minecraft version. Please update it as there's no build for 0.3
