### ISSUE TITLE
Bow's xp go wrong

### ISSUE THREAD

**Issue by tgh666** [embeddedt/TinkerLeveling#4]
If you want to make your bow level up, you need attack instead of shoot an arrow.
Please fix it.

**Comment by MinecrackTyler** [comment]
Just adding that this is also the case with the Tinker's archery mod for 1.16, however that is a mod and not part of TC so that probably requires a separate fix if you are willing to add support for it

**Comment by embeddedt** [comment]
Native Tinkers bows will now level in the latest 1.18 release. No plans to backport this to 1.16.
