### ISSUE TITLE
TinkerLeveling breaks Refined Storage autocrafting

### ISSUE THREAD

**Issue by PatiHox** [embeddedt/TinkerLeveling#6]
I am running Minecraft 1.16.5 with Forge 36.2.39, my mod list is as follows:

- Just Enough Items 7.7.1.1004
- Mantle 1.6.157
- Refined Storage 1.9.18
- Tinker Leveling 0.2.0
- Tinkers' Construct 3.3.4.335

## Issue description:
After installing Tinker Leveling it is no longer possible to autocraft items in Refined Storage.

## Steps to reproduce

1. Using RS's Crafting Grid create pattern for crafting refinedstorage:raw_basic_processor and pattern for refinedstorage:basic_processor
2. Insert these patterns into RS's Crafter block
3. Try to request crafting refinedstorage:basic_processor

## Expected result
Resources needed for crafting refinedstorage:raw_basic_processor are displayed

## Actual result
Missing refinedstorage:raw_basic_processor message is displayed

**Comment by PatiHox** [comment]
Fixed in #7

**Comment by embeddedt** [comment]
Released this to CF, sorry for the delay.
