### ISSUE TITLE
Crash [1.16.5] Error: java.lang.IllegalStateException: Tag tconstruct:modifiable used before it was bound

### ISSUE THREAD

**Issue by JNCHGTR** [embeddedt/TinkerLeveling#9]
Minecraft ver: 1.16.5
Forge ver: 36.2.34
Mod version: 0.3.0

Crash whenever I go into the "Controls" menu

Using the mod in my modpack

Doesn't cause a crash when I go into "Controls" with the mod disabled.

Crash report - https://gist.github.com/JNCHGTR/1af1a2e0da63593d39a7f85dde027032

[crash-2023-04-25_10.05.51-client.txt](https://github.com/embeddedt/TinkerLeveling/files/11325485/crash-2023-04-25_10.05.51-client.txt)

**Comment by embeddedt** [comment]
Thanks; should be fixed in 0.3.1.

**Comment by JNCHGTR** [comment]
> Thanks; should be fixed in 0.3.1.

Wooo! Looking forward to it! I love the mod and since Tinker's is a staple in my pack I really want it to work <3

Thanks!

**Comment by embeddedt** [comment]
It's approved on CurseForge already. :)
